### PR TITLE
Add balena.yml to project

### PR DESCRIPTION
**Pull request by andrewnhem**
This allows us to submit your great project to balenaHub
(https://hub.balena.io)

- Adds the YML file to compile metadata for Hub
- Adds placeholder logo (feel free to replace)

Change-type: patch
Signed-off-by: Andrew Nhem <andrew@balena.io>

### CODE REVIEW

**Comment by andrewnhem** [comment]
@abhatikar I realize that this also relies on https://github.com/abhatikar/package-monitor/tree/main/package_detection being merged haha. My fault here.

**Comment by abhatikar** [comment]
Hey @andrewnhem, would love to add it to balena hub. Let me test this out first as Always AI has changed their working model recently which might have broken the tooling. Did you test it by any chance?

**Comment by andrewnhem** [comment]
I plan on testing this soon. Thanks for the note about the AlwaysAI model. It'll probably be a week or so before I test. Please let me know of newer instructions than the branch that you shared with us and I'm more than happy to try it out.

**Comment by abhatikar** [comment]
Sure will do.

**Comment by abhatikar** [comment]
@andrewnhem I have made some changes to make this work by pinning the alwaysAI version to 0.17.1. Could you please test and let me know if you are able to setup without any issues. PRs welcome.

**Pull request merged**
